### PR TITLE
Pull chinese

### PR DESCRIPTION
**Pull request by markthink**
@chenopis  This is the k8smeetup translation library overall submission，some documents have not been proofread, and after that I still need some time to compare the previously translated documents。

### CODE REVIEW

**Comment by chenopis** [comment]
@markthink We need to get all of the contributors to sign the CNCF CLA (Contributor License Agreement) otherwise this won't pass the `cla/linuxfoundation` check. Also, the conflicts will need to be resolved before this can be merged.

**Comment by markthink** [comment]
@chenopis I am fix it on submission.

**Comment by lichuqiang** [comment]
@markthink I would suggest we keep the commit history when moving the repo, for better backward tracking :)

**Comment by chenopis** [comment]
@lichuqiang The issue is: if we keep the commit history, we need to have all of the contributors sign the CNCF CLA. Can you generate a list of contributors and make sure they have all signed the CLA?

**Comment by lichuqiang** [comment]
Oh, sorry that I didn't realized the CLA issue. 
I noticed that @markthink has informed the guys to sign the CNCF CLA in wechat group, not sure how's it going.
But I agree that it could be difficult to make sure all the guys signed, as some of them may not  concentrate on the area anymore. So re-generate a commit to avoid the CLA issue could be a good idea to some extent.

**Comment by chenopis** [comment]
@deepak-vij @dhilipkumars Do you guys have any opinion how this should be handled?

**Comment by dhilipkumars** [comment]
@chenopis Its a Big contribution, of course the initial one, if other contributors do not have any objection, we could merge this in and get started with ?

**Comment by dhilipkumars** [comment]
@markthink seems to have signed the CLA

**Comment by chenopis** [comment]
@dhilipkumars Ok, I'm fine w/ merging this. Just wanted to make sure you were okay w/ moving things over w/o the commit history.

**Pull request merged**
