### PR TITLE
Translate docs/tasks/job/coarse-parallel-processing-work-queue/index.md

### PR DESCRIPTION
**Pull request by linyouchong**
Restorn from https://raw.githubusercontent.com/kubernetes/kubernetes-docs-zh/master-bak-2018-07-21/docs/tasks/job/coarse-parallel-processing-work-queue/index.md

### CODE REVIEW

**Review by markthink — COMMENTED** [review]
感谢重新提交，修复之前的翻译内容。

**Comment by markthink** [comment]
@linyouchong 文件冲突需要解决一下..

**Comment by tengqm** [comment]
This translation is very good. Please solve the conflicts so that we can merge it. Thanks.

**Comment by markthink** [comment]
@linyouchong 文件冲突需要解决一下..

**Pull request closed without merging**
