### PR TITLE
Ignore jekyll generated files and remove them from the repo

### PR DESCRIPTION
**Pull request by sn00011**
This pull request is meant to resolve the issue #32, please review.

### CODE REVIEW

**Comment by sn00011** [comment]
I signed it!

**Comment by iT2afL0rd** [comment]
@hurf  What do you think about it ?

**Comment by linfan** [comment]
From the content of the files, I have a feeling that some of those are not "auto-generated" ...

**Comment by iT2afL0rd** [comment]
It is generated by Jekyll. @linfan

**Comment by hurf** [comment]
I've tried to delete all the files under folders added in .gitignore file. And Jelyll can re-generate them.

I'm not clear about how github serves kubernetes.github.io, maybe these contents are needed in that repo, but for this repo, I think they can be deleted.

**Pull request closed without merging**
