### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR:
- Updates OWNERS with a current and more limited list of approvers and reviewers.

@hanjiayao 👋 Questions for you:
- Who on your team would you like to have [reviewer/approver](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer) status?
- Who on your team would you like to have repo admin permissions?

/assign @chenopis

### CODE REVIEW

**Comment by zacharysarah** [comment]
@spiffxp 👋 In both this PR and https://github.com/kubernetes/kubernetes-docs-zh/pull/497#issuecomment-414428304, despite @Bradamant3 and myself being approvers in [kubernetes-docs-zh/OWNERS](https://github.com/kubernetes/kubernetes-docs-zh/blob/master/OWNERS), k8s-ci-robot seems sluggish in either adding an approval or an error message. Any suggestions? Otherwise, I can use my admin powers to manually merge. Thanks in advance! 🙇

**Comment by spiffxp** [comment]
@zacharysarah I'm willing to bet the `approve` plugin isn't turned on for this repo, ref: https://github.com/kubernetes/test-infra/issues/6227

If you'd like to, you can PR this into k/test-infra yourself.  You can also open an issue and assign to me and I'll move forward on it without seeking lazy consensus, given that the request is coming from someone in the OWNERS file.

**Comment by zacharysarah** [comment]
@spiffxp Thanks! [Done](https://github.com/kubernetes/test-infra/pull/9100).

**Comment by zacharysarah** [comment]
ping @chenopis 👋 
needs LGTM

**Comment by stewart-yu** [comment]
If wrong, please correct me:grinning:
IMO, i'm Chinese, own in `cn` repo good for me yet.  BTW, due to contribution in `website` docs repo and `kubernetes` core repo, i apply for to be `approver`, if not mind?

**Comment by zacharysarah** [comment]
@Bradamant3 👋 Would you mind tagging this again with a `/lgtm`, please?

**Comment by zacharysarah** [comment]
@stewart-yu 👋 
> i apply for to be approver, if not mind?

That sounds great to me. Please work with @hanjiayao to see what the team's needs are! 

/cc @tengqm

**Review by tengqm — APPROVED** [review]
/lgtm

**Pull request merged**
