### PR TITLE
translate Resource-Usage-Monitoring-Kubernetes.md

### PR DESCRIPTION
**Pull request by jl2005**

### CODE REVIEW

**Comment by jl2005** [comment]
i signed it

**Comment by xiangpengzhao** [comment]
@jl2005 please follow the instructions at https://github.com/kubernetes/kubernetes-docs-zh/pull/561#issuecomment-423029314 and double check the status in your CLA registration page. If it's still not resolved, please contact helpdesk@rt.linuxfoundation.org for help :)

**Pull request closed without merging**
