### PR TITLE
'api-reference-v1.8-pr-2017-12-07'

### PR DESCRIPTION
**Pull request by WinSon-XiaoYin**

### CODE REVIEW

**Comment by lichuqiang** [comment]
To get your PR in, you need to sign the CLA first :)

**Comment by WinSon-XiaoYin** [comment]
I have sign a Contributor License Agreement (CLA), please recheck.

**Comment by WinSon-XiaoYin** [comment]
I have signed a Contributor License Agreement (CLA), please recheck.

**Comment by xiaosuiba** [comment]
You may also need to check the `email account` used in your commits.
It should be the same as the one in your *CLA account*.
`git config user.email`

**Comment by markthink** [comment]
@WinSon-XiaoYin 需要解决一下冲突，可以先更新一下代码库，再提交一次。

**Review by markthink — COMMENTED** [review]
另外中英文之间应该用空格分隔，格式稍注意一下。

**Comment by markthink** [comment]
@WinSon-XiaoYin 需要解决一下冲突，再提交..谢谢。

**Comment by markthink** [comment]
@WinSon-XiaoYin [译者列表](https://docs.google.com/spreadsheets/d/1nHCp-wHf26lqcah9CVQpPaiSFxqVrsdFlCyRyHCjz80/edit#gid=0)没有看到您

可以参考此链接加入：https://k8smeetup.github.io/chart

**Pull request closed without merging**
