### PR TITLE
Fix external link failed

### PR DESCRIPTION
**Pull request by Mr-Linus**

### CODE REVIEW

**Review by tengqm — APPROVED** [review]
/lgtm
/approve

**Comment by Mr-Linus** [comment]
I sign it.

**Comment by Mr-Linus** [comment]
I have signed the CNCF CLA. Why does this PR have no CNCF-CLA:YES label? @tengqm @zhangxiaoyu-zidif

**Comment by tengqm** [comment]
@Mr-Linus pls check your email address used for signing CLA and the one you used for submitting the PR.

**Comment by Mr-Linus** [comment]
Solved, thanks. @tengqm

**Pull request merged**
